package com.ramira.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.Data;

import java.time.Instant;
import java.util.List;

/**
 * The complete order payload that the frontend POSTs to /api/orders.
 *
 * Field names match the JS orderPayload object exactly so Jackson
 * can deserialise without any custom mapping.
 */
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderRequestDto {

    /* ── Customer details ── */

    @NotBlank(message = "customerName is required")
    private String customerName;

    @NotBlank(message = "contactNumber is required")
    @Pattern(regexp = "^\\+91[6-9]\\d{9}$", message = "contactNumber must be a valid Indian mobile (+91XXXXXXXXXX)")
    private String contactNumber;

    // Optional — no validation constraint beyond format if present
    @Pattern(regexp = "^(\\+91[6-9]\\d{9})?$", message = "altContactNumber must be a valid Indian mobile or empty")
    private String altContactNumber;

    @NotBlank(message = "fullAddress is required")
    @Size(min = 10, message = "fullAddress seems too short")
    private String fullAddress;

    @NotBlank(message = "pincode is required")
    @Pattern(regexp = "^\\d{6}$", message = "pincode must be 6 digits")
    private String pincode;

    @NotBlank(message = "city is required")
    private String city;

    @NotBlank(message = "state is required")
    private String state;

    /* ── Order lines ── */

    @NotNull @Size(min = 1, message = "Order must contain at least one item")
    @Valid
    private List<OrderItemDto> items;

    /* ── Totals (trusted for display only; server recalculates for safety) ── */

    private Double subtotal;
    private Double shipping;
    private Double total;

    /** ISO-8601 timestamp generated by the browser */
    private Instant orderedAt;
}
